[package]
name = "transmute-crt"
version = "0.1.0"
edition = "2021"

[features]
# compile GC with test mode support (see compiler flag GC_TEST in gc.c)
gc-test = []
# compile GC with logs support (see compiler flag GC_LOGS in gc.c)
gc-logs = []