[package]
name = "transmute-runtime"
version = "0.1.0"
edition = "2021"

[features]
default = ["gc-cc-dbg", "gc-pthread"]
gc-test = []
gc-logs = []
gc-logs-stable = ["gc-logs"]
gc-logs-colors = ["gc-logs"]
gc-functions = []
gc-cc-dbg = []
gc-pthread = []