[package]
name = "transmute-rustcrt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
transmute-rustcrt-macros = { path = "../rust-c-macros" }

[features]
gc-test = []
gc-logs = []
