[package]
name = "tmc"
version = "0.1.0"
edition = "2021"

[dependencies]
transmute-core = {path = "../core" }
transmute-ast = {path = "../ast" }
transmute-hir = {path = "../hir" }
transmute-crt = {path = "../rt/c" }
transmute-llvm = {path = "../llvm" }
clap = { version = "4.5.8", features = ["derive"] }

[dev-dependencies]
