[package]
name = "transmute-mir"
version = "0.1.0"
edition = "2021"

[dependencies]
transmute-core = { path = "../core" }
transmute-hir = { path = "../hir" }

[dev-dependencies]
transmute-ast = {path = "../ast"}
transmute-nst = {path = "../nst"}
insta = "1.34.0"

